export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export enum EntityType {
  USER = 'USER',
  USER_PROFIL = 'USER_PROFIL',
  TOOL = 'TOOL',
  TOOL_REQUEST = 'TOOL_REQUEST',
  RESERVATION = 'RESERVATION',
  WAREHOUSE = 'WAREHOUSE',
  WAREHOUSE_MANAGER = 'WAREHOUSE_MANAGER',
  CATEGORY = 'CATEGORY',
  AUDIT_LOG = 'AUDIT_LOG',
  APPLICANT_REQUEST = 'APPLICANT_REQUEST',
  VERIFICATION_CODE = 'VERIFICATION_CODE',
  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST',
  INVALID_TOKEN = 'INVALID_TOKEN',
  SETTINGS = 'SETTINGS',
}
